import dotenv from 'dotenv';
import path from 'fs'; 
dotenv.config();

export const ENV = {
  PORT: process.env.PORT,
  NODE_ENV: process.env.NODE_ENV,
  DATABASE_URL: process.env.DATABASE_URL ?? '',
  CLERK_PUBLISHABLE_KEY: process.env.CLERK_PUBLISHABLE_KEY,
  CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY,
  RISK_ARTIFACTS_DIR: process.env.RISK_ARTIFACTS_DIR,
  RISK_DATASET_LOOKBACK_HOURS: process.env.RISK_DATASET_LOOKBACK_HOURS,
  RISK_SHADOW_LOOKBACK_MINUTES:  process.env.RISK_SHADOW_LOOKBACK_MINUTES,
  RISK_SUPERVISED_WEIGHT: process.env.RISK_SUPERVISED_WEIGHT,
  RISK_ANOMALY_WEIGHT: process.env.RISK_ANOMALY_WEIGHT,
  RISK_BAND_HIGH_THRESHOLD: process.env.RISK_BAND_HIGH_THRESHOLD,
  RISK_BAND_CRITICAL_THRESHOLD:  process.env.RISK_BAND_HIGH_THRESHOLD,
};