version: "3.9"

services:

  user-service:
    build: ./backend/services/user-service
    ports:
      - "5000:5000"
    volumes:
      - ./backend/services/user-service:/app
      - ./backend/prisma:/prisma
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:admin@host.docker.internal:5432/sacvs_db?schema=public
      - PRISMA_SCHEMA_PATH=/prisma/schema.prisma
    command: sh -c "cp /prisma/schema.prisma /app/schema.prisma && npx prisma generate --schema /app/schema.prisma && npm run dev"

  credential-service:
    build: ./backend/services/credential-service
    ports:
      - "5100:5100"
    volumes:
      - ./backend/services/credential-service:/app
      - ./backend/prisma:/prisma
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:admin@host.docker.internal:5432/sacvs_db?schema=public
      - PRISMA_SCHEMA_PATH=/prisma/schema.prisma
    command: sh -c "cp /prisma/schema.prisma /app/schema.prisma && npx prisma generate --schema /app/schema.prisma && npm run dev"

  gateway:
    build: ./backend/gateway
    ports:
      - "4000:4000"
    volumes:
      - ./backend/gateway:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - USER_SERVICE_URL=http://user-service:5000
      - CREDENTIALS_SERVICE_URL=http://credential-service:5100

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
